const List<String> encouragingSlogans = [
  "So {habitNumber} times, huh? You're on fire 🔥🔥🔥!",
  "Look at you, {habitNumber} times strong! 💪 Keep going!",
  "{habitNumber} times? You're crushing it! 🏆💥",
  "Whoa, {habitNumber} already? You're unstoppable! 🚀🔥",
  "Boom! {habitNumber} times! Nothing can stop you now 💯",
  "Keep it up! {habitNumber} times and you're a champion 🏅🙌",
  "You just hit {habitNumber} times like a pro! 🏆⚡️",
  "Look at you go, {habitNumber} times down, you're doing amazing! 🎯",
  "So {habitNumber} times in, huh? Keep the momentum going 🔥🔥🔥!",
  "Nice! {habitNumber} times and counting. You're getting better every day 🎯✨",
  "Wow, {habitNumber} already? You're making it look easy 💥💪",
  "How about that! {habitNumber} times, and you're doing great 🌍🙌",
  "Did someone say {habitNumber} times? You're unstoppable! 🚀🔥",
  "30? More like 30 reasons to celebrate! 🎉🎉 Keep it going!",
  "Look at that, {habitNumber} times! You're getting better every day! 🏅💪",
  "Keep going, {habitNumber} in, and the best is yet to come! 🚀💫",
  "Big milestone: {habitNumber} times! Time to celebrate 🎉🍾",
  "You did it, {habitNumber} times! Now, that's some serious progress! 💯🏆",
  "Nice, {habitNumber}? Feels like you're ready for the next step! 🕹️✨",
  "So {habitNumber} in and you’re still going strong! 🔥🚀",
  "Number {habitNumber} and you’re on top of your game! 💪🎯",
  "Boom! {habitNumber}! 🔥🏅",
  "You're on fire, {habitNumber} and counting! 🔥🔥🔥",
  "Can’t stop, won’t stop! {habitNumber} and counting 🏅🎉",
];